'use client';

import { useEffect, useRef, useState, type ReactNode } from 'react';
import { Loader2 } from 'lucide-react';
import { Button } from '@/components/ui/button';
import { PageCitationChip } from '@/components/chat/PageCitationChip';
import { parseCitationPages } from '@/lib/ai/summary-validation';
import { isBuilt } from '@/lib/capabilities';
import type { Contract, SummaryStatus } from '@/types/domain';

/**
 * Contract summary card (spec 07 v1.1 §B, US-015). Owns its own state machine:
 *   pending    → one POST /summary (409 ⇒ treat as processing)
 *   processing → poll GET every 2 s for 30 s, then every 10 s; stale ⇒ Generate
 *   error/none → Generate summary button
 *   completed  → Markdown with [Page X] chips
 * Hidden entirely while `extract.summary` is not built (P-6).
 */
const POLL_FAST_MS = 2_000;
const POLL_SLOW_MS = 10_000;
const FAST_WINDOW_MS = 30_000;

type View = { status: SummaryStatus; md: string | null; uncited: boolean; stale: boolean };

export function SummaryCard({ contract }: { contract: Contract }) {
  const [view, setView] = useState<View>({
    status: contract.summary_status ?? 'none',
    md: contract.summary_md ?? null,
    uncited: Boolean(contract.summary_uncited),
    stale: Boolean(contract.summary_claim_stale),
  });
  const [slow, setSlow] = useState(false);
  const [posting, setPosting] = useState(false);
  const postedOnce = useRef(false);
  const reclaimedOnce = useRef(false);

  async function generate(): Promise<void> {
    if (posting) return;
    setPosting(true);
    try {
      const res = await fetch(`/api/contracts/${contract.id}/summary`, { method: 'POST' });
      if (res.status === 409) {
        // Another path holds the claim — treat as processing and poll.
        setView((v) => ({ ...v, status: 'processing', stale: false }));
        return;
      }
      if (!res.ok) {
        setView((v) => ({ ...v, status: 'error' }));
        return;
      }
      const body = (await res.json()) as { summary_md: string | null; summary_status: SummaryStatus; summary_uncited?: boolean };
      setView({ status: body.summary_status, md: body.summary_md, uncited: Boolean(body.summary_uncited), stale: false });
    } catch {
      setView((v) => ({ ...v, status: 'error' }));
    } finally {
      setPosting(false);
    }
  }

  // pending ⇒ exactly one POST; a stale processing claim on load ⇒ one reclaim.
  useEffect(() => {
    if (view.status === 'pending' && !postedOnce.current) {
      postedOnce.current = true;
      void generate();
    }
    if (view.status === 'processing' && view.stale && !reclaimedOnce.current) {
      reclaimedOnce.current = true;
      void generate();
    }
    // eslint-disable-next-line react-hooks/exhaustive-deps
  }, [view.status, view.stale]);

  // processing ⇒ poll GET until completed/error; never a second POST while fresh.
  useEffect(() => {
    if (view.status !== 'processing' || posting) return;
    const startedAt = Date.now();
    let timer: ReturnType<typeof setTimeout> | undefined;
    let cancelled = false;
    const tick = async () => {
      try {
        const res = await fetch(`/api/contracts/${contract.id}`);
        if (res.ok) {
          const { contract: c } = (await res.json()) as { contract: Contract };
          if (cancelled) return;
          if (c.summary_status === 'completed' || c.summary_status === 'error') {
            setView({ status: c.summary_status, md: c.summary_md ?? null, uncited: Boolean(c.summary_uncited), stale: false });
            return;
          }
          if (c.summary_claim_stale) {
            setView((v) => ({ ...v, stale: true }));
            return;
          }
        }
      } catch {
        // keep polling
      }
      if (cancelled) return;
      const elapsed = Date.now() - startedAt;
      if (elapsed > FAST_WINDOW_MS) setSlow(true);
      timer = setTimeout(tick, elapsed > FAST_WINDOW_MS ? POLL_SLOW_MS : POLL_FAST_MS);
    };
    timer = setTimeout(tick, POLL_FAST_MS);
    return () => {
      cancelled = true;
      if (timer) clearTimeout(timer);
    };
  }, [view.status, posting, contract.id]);

  if (!isBuilt('extract.summary')) return null;

  return (
    <section aria-label="Summary" className="mb-subsection flex flex-col gap-2 rounded-card border border-grey-100 p-4">
      <h2 className="text-h5 text-grey-900">Summary</h2>

      {view.status === 'completed' && view.md && (
        <>
          <div className="flex flex-col gap-2 text-body text-grey-700">{renderMarkdown(view.md)}</div>
          <p className="text-caption text-grey-400">≤ 200 words · generated by AI</p>
          {view.uncited && (
            <p role="note" className="text-caption text-warning-900">
              Some statements in this summary could not be tied to a page — verify them in the document.
            </p>
          )}
        </>
      )}

      {(view.status === 'pending' || (view.status === 'processing' && !view.stale)) && (
        <div role="status" className="flex items-center gap-2 text-caption text-grey-500">
          <Loader2 aria-hidden="true" className="h-4 w-4 animate-spin text-brand-500" />
          {slow ? 'Still writing the summary…' : 'Writing the summary…'}
        </div>
      )}

      {((view.status === 'processing' && view.stale) || view.status === 'error' || view.status === 'none') && (
        <div className="flex flex-col gap-2">
          {view.status === 'error' && (
            <p role="alert" className="text-caption text-danger-700">
              We couldn&apos;t write a summary for this contract.
            </p>
          )}
          <Button onClick={() => void generate()} disabled={posting} className="self-start">
            Generate summary
          </Button>
        </div>
      )}
    </section>
  );
}

/**
 * Minimal Markdown: headings become bold, `- ` lists are kept, **bold** kept,
 * and every [Page X] becomes a PageCitationChip that jumps the viewer.
 */
export function renderMarkdown(md: string): ReactNode[] {
  const blocks: ReactNode[] = [];
  let list: ReactNode[] = [];
  const flushList = () => {
    if (list.length > 0) {
      blocks.push(
        <ul key={`ul-${blocks.length}`} className="list-disc pl-5">
          {list}
        </ul>,
      );
      list = [];
    }
  };
  md.split('\n').forEach((raw, i) => {
    const line = raw.replace(/^\s*#{1,6}\s+(.+)$/, '**$1**').trim();
    if (line.length === 0) {
      flushList();
      return;
    }
    const bullet = line.match(/^[-*•]\s+(.*)$/);
    if (bullet) {
      list.push(<li key={`li-${i}`}>{inline(bullet[1]!, i)}</li>);
      return;
    }
    flushList();
    blocks.push(<p key={`p-${i}`}>{inline(line, i)}</p>);
  });
  flushList();
  return blocks;
}

function inline(text: string, key: number): ReactNode[] {
  const out: ReactNode[] = [];
  // L8: one bracket may name several pages — "[Page 1, 5, 7]", "[Pages 3–4]".
  // Each page gets its own chip, sharing the parser the validator uses so the
  // card and the citation check can never disagree about what was cited.
  const parts = text.split(/(\[Pages?\s+[^\]]*\d[^\]]*\]|\*\*[^*]+\*\*)/g);
  parts.forEach((part, i) => {
    if (/^\[Pages?\s+[^\]]*\d[^\]]*\]$/i.test(part)) {
      const pages = parseCitationPages(part);
      pages.forEach((page) => out.push(<PageCitationChip key={`${key}-${i}-${page}`} page={page} />));
      if (pages.length > 0) return;
    }
    const bold = part.match(/^\*\*([^*]+)\*\*$/);
    if (bold) {
      out.push(<strong key={`${key}-${i}`}>{bold[1]}</strong>);
      return;
    }
    if (part.length > 0) out.push(<span key={`${key}-${i}`}>{part}</span>);
  });
  return out;
}
